name: Build Action

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      target_os:
        description: Target OS
        type: choice
        options:
          - android
          - ios
          - linux
          - mac
          - win
          - wasm
      target_cpu:
        description: Target CPU
        type: choice
        options:
          - arm
          - arm64
          - x64
          - x86
          - wasm
      target_environment:
        description: Target environment
        type: choice
        default: ""
        options:
          - ""
          - device
          - catalyst
          - simulator
          - musl
      staticlib:
        description: Static Library
        type: boolean
        required: false
        default: true
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      emsdk_version:
        description: Emscripten SDK
        type: string
        required: false
        default: 3.1.34

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      target_os: ${{ github.event.inputs.target_os }}
      target_cpu: ${{ github.event.inputs.target_cpu }}
      target_environment: ${{ github.event.inputs.target_environment }}
      enable_v8: ${{ github.event.inputs.enable_v8 == 'true' }}
      emsdk_version: ${{ github.event.inputs.emsdk_version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      staticlib: ${{ github.event.inputs.staticlib == 'true' }}
