name: Build

on:
  workflow_call:
    inputs:
      branch:
        description: PDFium branch
        type: string
        required: false
        default: main
      version:
        description: PDFium version
        type: string
        required: false
        default: ""
      target_os:
        description: Target OS (android|ios|linux|mac|wasm|win)
        type: string
        required: true
      target_cpu:
        description: Target CPU (arm|arm64|x64|x86|wasm)
        type: string
        required: true
      target_environment:
        description: Target environment (device|catalyst|simulator|musl)
        type: string
        required: false
        default: ""
      staticlib:
        description: Static Library
        type: boolean
        required: false
        default: true
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      emsdk_version:
        description: Emscripten SDK
        type: string
        required: false
        default: 3.1.34
    outputs:
      artifact:
        description: "The name of the artifact"
        value: ${{ jobs.build.outputs.artifact }}

jobs:
  build:
    outputs:
      artifact: ${{ steps.init.outputs.artifact }}
    runs-on: ${{ (inputs.target_os == 'ios' || inputs.target_os == 'mac') && 'macos-latest' || inputs.target_os == 'win' && 'windows-2022' || 'ubuntu-22.04' }}
    steps:
      - name: Initialize
        id: init
        shell: bash
        run: |
          ARTIFACT="pdfium"
          [ "${{inputs.enable_v8}}" == "true" ] && ARTIFACT="$ARTIFACT-v8"
          ARTIFACT="$ARTIFACT-${{inputs.target_os}}"
          [ "${{inputs.target_environment}}" != "" ] && ARTIFACT="$ARTIFACT-${{inputs.target_environment}}"
          [ "${{inputs.target_os}}" != "${{inputs.target_cpu}}" ] && ARTIFACT="$ARTIFACT-${{inputs.target_cpu}}"
          [ "${{inputs.is_debug}}" == "true" ] && ARTIFACT="$ARTIFACT-debug"
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Install Tools
        uses: extractions/setup-just@v2
      - name: Set environment variables
        shell: bash
        run: |
          cat >> .env <<END
          target_os = "${{inputs.target_os}}"
          target_cpu = "${{inputs.target_cpu}}"
          is_debug = ${{inputs.is_debug}}
          pdf_is_complete_lib = ${{inputs.staticlib}}
          END
          echo "${PWD}/depot_tools" >> $GITHUB_PATH
      - name: Build
        shell: bash
        run: |
          just build
      - name: Configure
        run: |
          cat <<END >>$GITHUB_STEP_SUMMARY
          ## args.gn

          \`\`\`gn
          $(cat pdfium/out/${{inputs.target_os}}/args.gn)
          \`\`\`
          END
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.init.outputs.artifact }}
          path: dist/
