name: Release

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: ios
            arch: arm64
            host: macos-latest
          - os: mac
            arch: arm64
            host: macos-latest
          - os: mac
            arch: x64
            host: macos-latest
          - os: win
            arch: arm64
            host: windows-latest
          - os: win
            arch: x64
            host: windows-latest
          - os: linux
            arch: arm64
            host: ubuntu-latest
            tool: gnu
          - os: linux
            arch: x64
            host: ubuntu-latest
            tool: gnu
          - os: linux
            arch: arm64
            host: ubuntu-latest
            tool: musl
          - os: linux
            arch: x64
            host: ubuntu-latest
            tool: musl

    name: Build ${{ matrix.targets.os }}-${{ matrix.targets.arch }}
    runs-on: ${{ matrix.targets.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Set Env
        run: |
          cat >> .env <<END
          TARGET_OS=${{ matrix.targets.os }}
          TARGET_CPU=${{ matrix.targets.arch }}
          END

          just build
