name: Release

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: ios
            arch: arm64
            host: macos-latest
          - os: mac
            arch: arm64
            host: macos-latest
          - os: mac
            arch: x64
            host: macos-latest
          - os: win
            arch: arm64
            host: windows-latest
          - os: win
            arch: x64
            host: windows-latest
          - os: linux
            arch: arm64
            host: ubuntu-latest
          - os: linux
            arch: x64
            host: ubuntu-latest
          - os: linux
            arch: arm64
            host: ubuntu-latest
            tool: musl
          - os: linux
            arch: x64
            host: ubuntu-latest
            tool: musl

    name: Build ${{ matrix.targets.os }}-${{ matrix.targets.arch }} ${{ matrix.targets.tool }}
    runs-on: ${{ matrix.targets.host }}

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Set Env
        shell: bash
        run: |
          cat >> .env <<END
          target_os = "${{ matrix.targets.os }}"
          target_cpu = "${{ matrix.targets.arch }}"
          END

          echo "${PWD}/depot_tools" >> $GITHUB_PATH

      - name: Build
        shell: bash
        run: |
          just build
